CREATE TABLE `customer` (
    `id` INT(11) NOT NULL AUTO_INCREMENT ,
    `FIRSTNAME` VARCHAR(20) NOT NULL DEFAULT '' ,
    `LASTNAME` VARCHAR(20) NOT NULL DEFAULT '' ,
    `BIRTHDATE` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
    `money` DECIMAL(10,2) NOT NULL DEFAULT '0.00' ,
    PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
